# Export some variable found by CMake


PARFLOW_VERSION_STRING="v3.6.0-42-g145fccd"
PARFLOW_VERSION="3.6.0"
PARFLOW_VERSION_MAJOR=3
PARFLOW_VERSION_MINOR=6
PARFLOW_VERSION_PATCH=0
PARFLOW_VERSION_HASH="145fccd"
PARFLOW_VERSION_EXTRA="42"

MPIEXEC="/Users/jackson/PFTree/OMPI-4.0.2/bin/mpiexec"
MPIEXEC_NUMPROC_FLAG="-n"
MPIEXEC_POSTFLAGS=""
MPIEXEC_PREFLAGS=""
